In [38]:
import pandas as pd

In [39]:
df = pd.read_csv('FIFA23.csv', delimiter=',',index_col=0)
df.head(4)

,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
ID,,,,,,,,,,,,,,,,,,,,,
209658,L. Goretzka,27,https://cdn.sofifa.net/players/209/658/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,87,88,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,€91M,...,Yes,SUB,"Jul 1, 2018",NaN,2026,189cm,82kg,€157M,8,NaN
212198,Bruno Fernandes,27,https://cdn.sofifa.net/players/212/198/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,86,87,Manchester United,https://cdn.sofifa.net/teams/11/30.png,€78.5M,...,Yes,LCM,"Jan 30, 2020",NaN,2026,179cm,69kg,€155M,8,NaN
224334,M. Acuña,30,https://cdn.sofifa.net/players/224/334/23_60.png,Argentina,https://cdn.sofifa.net/flags/ar.png,85,85,Sevilla FC,https://cdn.sofifa.net/teams/481/30.png,€46.5M,...,No,LB,"Sep 14, 2020",NaN,2024,172cm,69kg,€97.7M,19,NaN
192985,K. De Bruyne,31,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,91,91,Manchester City,https://cdn.sofifa.net/teams/10/30.png,€107.5M,...,Yes,RCM,"Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17,NaN

In [40]:
df['Value']

ID
209658       €91M
212198     €78.5M
224334     €46.5M
192985    €107.5M
224232     €89.5M
           ...
269127      €100K
267461      €210K
269526      €100K
267946      €100K
270567       €70K
Name: Value, Length: 12619, dtype: object

In [41]:
df['Wage'].values

array(['€115K', '€190K', '€46K', ..., '€500', '€500', '€2K'], dtype=object)

In [42]:
df['Wage'] = df['Wage'].replace('','€')

In [43]:
df['Wage'].values

array(['€115K', '€190K', '€46K', ..., '€500', '€500', '€2K'], dtype=object)

In [44]:
# Função para converter valores da coluna
def convert_wage(value):
    if pd.isna(value):
        return None
    value = value.replace('€', '')
    try:
        if 'M' in value:
            return float(value.replace('M', '')) * 1e6
        elif 'K' in value:
            return float(value.replace('K', '')) * 1e3
        else:
            return float(value)
    except ValueError:
        return None

# Aplicar a função de conversão à coluna 'Wage'
df['Wage'] = df['Wage'].apply(convert_wage)
df['Value'] = df['Value'].apply(convert_wage)
df['Release Clause'] = df['Release Clause'].apply(convert_wage)

In [45]:
df.head()

,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
ID,,,,,,,,,,,,,,,,,,,,,
209658,L. Goretzka,27,https://cdn.sofifa.net/players/209/658/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,87,88,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,91000000.0,...,Yes,SUB,"Jul 1, 2018",NaN,2026,189cm,82kg,157000000.0,8,NaN
212198,Bruno Fernandes,27,https://cdn.sofifa.net/players/212/198/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,86,87,Manchester United,https://cdn.sofifa.net/teams/11/30.png,78500000.0,...,Yes,LCM,"Jan 30, 2020",NaN,2026,179cm,69kg,155000000.0,8,NaN
224334,M. Acuña,30,https://cdn.sofifa.net/players/224/334/23_60.png,Argentina,https://cdn.sofifa.net/flags/ar.png,85,85,Sevilla FC,https://cdn.sofifa.net/teams/481/30.png,46500000.0,...,No,LB,"Sep 14, 2020",NaN,2024,172cm,69kg,97700000.0,19,NaN
192985,K. De Bruyne,31,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,91,91,Manchester City,https://cdn.sofifa.net/teams/10/30.png,107500000.0,...,Yes,RCM,"Aug 30, 2015",NaN,2025,181cm,70kg,198900000.0,17,NaN
224232,N. Barella,25,https://cdn.sofifa.net/players/224/232/23_60.png,Italy,https://cdn.sofifa.net/flags/it.png,86,89,Inter,https://cdn.sofifa.net/teams/44/30.png,89500000.0,...,Yes,RCM,"Sep 1, 2020",NaN,2026,172cm,68kg,154400000.0,23,NaN

In [46]:
df['Wage']

ID
209658    115000.0
212198    190000.0
224334     46000.0
192985    350000.0
224232    110000.0
            ...
269127       500.0
267461       500.0
269526       500.0
267946       500.0
270567      2000.0
Name: Wage, Length: 12619, dtype: float64

In [47]:
df['Value']

ID
209658     91000000.0
212198     78500000.0
224334     46500000.0
192985    107500000.0
224232     89500000.0
             ...
269127       100000.0
267461       210000.0
269526       100000.0
267946       100000.0
270567        70000.0
Name: Value, Length: 12619, dtype: float64

In [48]:
df.columns

Index(['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value', 'Wage', 'Special', 'Preferred Foot',
       'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate',
       'Body Type', 'Real Face', 'Position', 'Joined', 'Loaned From',
       'Contract Valid Until', 'Height', 'Weight', 'Release Clause',
       'Kit Number', 'Best Overall Rating'],
      dtype='object')

In [49]:
colunas = ['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value (€)', 'Wage (€)', 'Special', 'Preferred Foot',
       'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate',
       'Body Type', 'Real Face', 'Position', 'Joined', 'Loaned From',
       'Contract Valid Until', 'Height', 'Weight', 'Release Clause (€)',
       'Kit Number', 'Best Overall Rating']

In [51]:
df.columns = colunas

In [52]:
df.columns

Index(['Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall', 'Potential',
       'Club', 'Club Logo', 'Value (€)', 'Wage (€)', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Joined', 'Loaned From', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause (€)', 'Kit Number', 'Best Overall Rating'],
      dtype='object')

In [53]:
df.to_csv('FIFA23.csv')